/** capabilities.toml 的 icon 名 → lucide 图标。
 *
 * 后端只给语义名（`icon = "wand"`），web 侧在这里映射；
 * 未识别的名字回落 Sparkles，不报错（新增图标不阻塞旧前端）。
 */

import {
  Activity,
  AlignLeft,
  ArrowLeftRight,
  AudioWaveform,
  BarChart3,
  BookOpen,
  Captions,
  Check,
  Clapperboard,
  Columns2,
  Compass,
  Crop,
  FileInput,
  FileOutput,
  FileText,
  Film,
  Frame,
  GitBranch,
  Image,
  ImagePlus,
  Images,
  Languages,
  LayoutTemplate,
  List,
  ListTree,
  Mic,
  Music,
  Music4,
  PenLine,
  PenTool,
  Quote,
  Radio,
  RectangleVertical,
  Scissors,
  Search,
  Shield,
  ShoppingBag,
  SlidersHorizontal,
  Smile,
  Sparkles,
  Stamp,
  Stethoscope,
  Users,
  Video,
  VolumeX,
  Wand2,
} from 'lucide-react'
import type { LucideIcon } from 'lucide-react'

const ICONS: Record<string, LucideIcon> = {
  activity: Activity,
  align: AlignLeft,
  'audio-waveform': AudioWaveform,
  'bar-chart': BarChart3,
  'book-open': BookOpen,
  captions: Captions,
  chart: BarChart3,
  check: Check,
  clapperboard: Clapperboard,
  columns: Columns2,
  compass: Compass,
  crop: Crop,
  'file-input': FileInput,
  'file-output': FileOutput,
  'file-text': FileText,
  film: Film,
  frame: Frame,
  'git-branch': GitBranch,
  image: Image,
  'image-plus': ImagePlus,
  images: Images,
  languages: Languages,
  layout: LayoutTemplate,
  list: List,
  'list-tree': ListTree,
  mic: Mic,
  music: Music,
  'music-4': Music4,
  pen: PenLine,
  'pen-tool': PenTool,
  quote: Quote,
  radio: Radio,
  'rectangle-vertical': RectangleVertical,
  scissors: Scissors,
  search: Search,
  shield: Shield,
  'shopping-bag': ShoppingBag,
  sliders: SlidersHorizontal,
  smile: Smile,
  stamp: Stamp,
  stethoscope: Stethoscope,
  swap: ArrowLeftRight,
  users: Users,
  video: Video,
  'volume-x': VolumeX,
  wand: Wand2,
}

export function capabilityIcon(name: string | null | undefined): LucideIcon {
  return (name && ICONS[name]) || Sparkles
}
